project:
  output-dir: _output

format:
  revealjs:
    theme: ../_shared/theme/cf_dark.scss
    slide-number: c/t
    navigation-mode: linear
    html-math-method: mathjax
    fig-align: center
    embed-resources: false

profile:
  default: reduced
  group:
    - [reduced, full]
